baseURL = "https://badran-elshenawy.netlify.app/"
languageCode = "en-us"
title = "Badran Elshenawy"
theme = "Coder"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true  # Allow raw HTML (important for Rmd rendering)

[params]
  author = "Badran Elshenawy"
  description = "Bioinformatician | R & Command-Line Enthusiast | High-Performance Computing | Git & Automation | Exploring Systems & Ideas"
  keywords = ["bioinformatics", "data science", "linux", "command-line", "HPC", "automation"]
  avatarURL = "images/personal_image_1.jpg"
  dateFormat = "January 2, 2006"
  since = 2025
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  colorScheme = "auto"  # Options: "auto", "dark", "light"
  hideColorSchemeToggle = false
  highlight = true  # Enable syntax highlighting
  rmd_files = ["Rmd"]  # Ensure `.Rmd` files are processed

# 🛠 GitHub commit footer (optional, for version tracking)
commit = "https://github.com/wolf5996/hugo-coder/tree/"

# 📡 RSS Feed
# [[params.social]]
# name = "RSS"
# icon = "fa-solid fa-rss fa-2x"
# weight = 6
# url = "https://yourwebsite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

# 🌍 Social Media & Links
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/badran-b-65414b113/"

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/wolf5996"

[[params.social]]
  name = "Oxford"
  icon = "fa-solid fa-university fa-2x"
  weight = 3
  url = "https://www.ndmrb.ox.ac.uk/team/badran-elshenawy"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 4
  url = "https://x.com/badranbadran230"

# 📌 Main Navigation Menu
[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

  